#!/usr/bin/env python
"""
SkyBound Journeys Database Management Script
"""
import os
import sys
import subprocess
import argparse
from pathlib import Path
from dotenv import load_dotenv
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("manage")

# Load environment variables from .env file
load_dotenv()

# Path to backend directory
BACKEND_DIR = Path(__file__).resolve().parent

# Add the project root to the Python path for imports to work
sys.path.append(str(BACKEND_DIR))

# Import after setting the path
import asyncio
from app.database.init_db import init_db, check_table_exists
# Import models to ensure they're loaded for Alembic
from app.models import Base

def run_alembic(args):
    """Run Alembic command with arguments"""
    command = ["alembic"] + args
    print(f"Running: {' '.join(command)}")
    process = subprocess.run(command, cwd=str(BACKEND_DIR))
    return process.returncode == 0

async def migrate():
    """Run database migrations"""
    logger.info("Running database migrations...")
    print("Running database migrations...")
    try:
        result = subprocess.run(
            ["alembic", "upgrade", "head"],
            cwd=str(BACKEND_DIR),
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            logger.info("✅ Migrations completed successfully!")
            print("\n✅ Migrations completed successfully!")
        else:
            logger.error(f"Migration failed: {result.stderr}")
            print(f"\n❌ Migration failed: {result.stderr}")
    except Exception as e:
        logger.error(f"Error running migrations: {e}", exc_info=True)
        print(f"\n❌ Error running migrations: {e}")

async def run_migrations():
    """Run all pending migrations"""
    # Initialize the database connection first
    await init_db()
    # Then run the migration using the migrate function
    await migrate()

def create_migration(name):
    """Create a new migration file based on SQLAlchemy model changes"""
    if not name:
        print("Error: Migration name is required")
        sys.exit(1)
    
    logger.info(f"Creating new migration based on SQLAlchemy model changes: {name}")
    print(f"Creating new migration based on SQLAlchemy model changes: {name}")
    
    if run_alembic(["revision", "--autogenerate", "-m", name]):
        print(f"✅ Created migration: {name}")
        print("\n⚠️ Please review the generated migration file in alembic/versions/ directory.")
        print("   Autogenerated migrations may need manual adjustments.")
    else:
        print("❌ Failed to create migration")
        sys.exit(1)

def migration_status():
    """Show migration status"""
    run_alembic(["current"])
    print("\nMigration history:")
    run_alembic(["history", "--verbose"])

async def db_status():
    """Check database status and tables"""
    await init_db()
    
    print("Database connection: Connected ✓")
    
    # Check for essential tables
    tables = ["users", "airlines", "airports", "flights", "bookings", "booking_flights", "passengers", "payments"]
    print("\nChecking tables:")
    
    for table in tables:
        exists = await check_table_exists(table)  # Use await since check_table_exists is now async
        status = "✓ Exists" if exists else "✗ Missing"
        print(f"  {table}: {status}")
        
    table_exists = [await check_table_exists(table) for table in tables]  # Use await with list comprehension
    if not all(table_exists):
        print("\n⚠️  Some tables are missing! Run migrations to create them.")
    else:
        print("\n✅ All essential tables exist.")

async def init_db_schema():
    """Generate initial schema from scratch"""
    try:
        logger.info("Installing PostgreSQL UUID extension...")
        print("Installing PostgreSQL UUID extension...")
        
        # Get PostgreSQL connection from env var
        pg_url = os.getenv("POSTGRES_URL", "")
        if pg_url and pg_url.startswith("postgresql://"):
            # Try to install the uuid-ossp extension directly
            try:
                result = subprocess.run(
                    ["psql", pg_url, "-c", "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"], 
                    capture_output=True, 
                    text=True
                )
                if result.returncode == 0:
                    print("✅ UUID extension installed or already exists")
                else:
                    print(f"⚠️ Warning: Could not install UUID extension: {result.stderr}")
            except Exception as e:
                print(f"⚠️ Warning: Error installing UUID extension: {e}")
        
        # Run migrations
        await migrate()
        print("✅ Initial schema applied successfully!")
    except Exception as e:
        logger.error(f"Failed to apply initial schema: {e}", exc_info=True)
        print(f"❌ Failed to apply initial schema: {e}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="SkyBound Journeys Database Management")
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # Migrate command
    migrate_parser = subparsers.add_parser("migrate", help="Run pending database migrations")
    
    # Create migration command
    create_parser = subparsers.add_parser("makemigration", help="Create a new migration")
    create_parser.add_argument("name", help="Name of the migration")
    
    # Status command
    status_parser = subparsers.add_parser("status", help="Show migration status")
    
    # DB status command
    dbstatus_parser = subparsers.add_parser("dbstatus", help="Check database status and tables")
    
    # Init schema command
    init_parser = subparsers.add_parser("initdb", help="Initialize database schema")
    
    args = parser.parse_args()
    
    if args.command == "migrate":
        asyncio.run(run_migrations())
    elif args.command == "makemigration":
        create_migration(args.name)
    elif args.command == "status":
        migration_status()
    elif args.command == "dbstatus":
        asyncio.run(db_status())
    elif args.command == "initdb":
        asyncio.run(init_db_schema())  # Use asyncio.run for async function
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
