"""Create profiles table without FK

Revision ID: 97104f13e472
Revises: b913e2af69d1
Create Date: 2025-07-10 15:38:32.265241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97104f13e472'
down_revision: Union[str, Sequence[str], None] = 'b913e2af69d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create profiles table, add foreign key, and set up trigger."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###

    # Manually add the foreign key constraint
    op.create_foreign_key(
        'fk_profiles_user_id',
        'profiles',
        'users',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='auth',
        ondelete='CASCADE'
    )

    # Create the trigger function
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER AS $$
    BEGIN
      INSERT INTO public.profiles (user_id, email, full_name, avatar_url)
      VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
      RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    # Create the trigger
    op.execute("""
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
    """)


def downgrade() -> None:
    """Drop the profiles table and the associated trigger."""
    # Drop the trigger
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    
    # Drop the trigger function
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")

    # Drop the profiles table
    op.drop_table('profiles', schema='public')

