"""Add indexes to all models for performance

Revision ID: c044ab7fa5d5
Revises: 9d7d84345b2a
Create Date: 2025-07-10 00:21:42.679793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c044ab7fa5d5'
down_revision: Union[str, Sequence[str], None] = '9d7d84345b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_airlines_code', 'airlines', ['code'], unique=False)
    op.create_index('ix_airports_iata_code', 'airports', ['iata_code'], unique=False)
    op.create_index('ix_bookings_user_id_created_at', 'bookings', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_flights_airline_id', 'flights', ['airline_id'], unique=False)
    op.create_index('ix_flights_departure_time', 'flights', ['departure_time'], unique=False)
    op.create_index('ix_flights_origin_dest_departure', 'flights', ['origin_airport_id', 'destination_airport_id', 'departure_time'], unique=False)
    op.create_index('ix_passengers_booking_id', 'passengers', ['booking_id'], unique=False)
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_index('ix_passengers_booking_id', table_name='passengers')
    op.drop_index('ix_flights_origin_dest_departure', table_name='flights')
    op.drop_index('ix_flights_departure_time', table_name='flights')
    op.drop_index('ix_flights_airline_id', table_name='flights')
    op.drop_index('ix_bookings_user_id_created_at', table_name='bookings')
    op.drop_index('ix_airports_iata_code', table_name='airports')
    op.drop_index('ix_airlines_code', table_name='airlines')
    # ### end Alembic commands ###
