name: Sky-Bound Journeys Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      # Add PostgreSQL service for backend tests if needed
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      # For testing purposes, we can use dummy values or set them as repository secrets
      SUPABASE_URL: "https://example.supabase.co"
      SUPABASE_KEY: "dummy-key-for-testing"
      SUPABASE_JWT_SECRET: "dummy-jwt-secret-for-testing"
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      TESTING: true
      # In production, use GitHub secrets:
      # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      # SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      # SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          pip install uv
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          uv pip install -e .
          uv add pytest pytest-asyncio httpx pytest-cov pytest-mock --dev
      
      - name: Run backend tests
        working-directory: ./backend
        run: |
          uv run pytest tests/ -v --cov=app
  
  frontend-tests:
    runs-on: ubuntu-latest
    
    env:
      # For testing purposes, we can use dummy values
      VITE_SUPABASE_URL: "https://example.supabase.co"
      VITE_SUPABASE_ANON_KEY: "dummy-anon-key-for-testing"
      # In production, use GitHub secrets:
      # VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      # VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test
